export default {
    carousel0: require('../assets/images/carousel0.png'),
    carousel1: require('../assets/images/carousel1.png'),
    carousel2: require('../assets/images/carousel2.png'),
    bg_focus: require('../assets/images/bg_focus.png'),
    avatar: require('../assets/images/avatar.png'),
    recommend: require('../assets/images/recommend.png'),
    item1: require('../assets/images/item1.png'),
    item2: require('../assets/images/item2.png'),
    item3: require('../assets/images/item3.png'),
    item4: require('../assets/images/item4.png'),
    item5: require('../assets/images/item5.png'),
    item6: require('../assets/images/item6.png'),
    details: require('../assets/images/details.png'),
}